IO.puts "Hello World!"
IO.puts "Here I Begin,"
IO.puts "To Curiously Learn,"
IO.puts "And Playfully Build"
IO.puts "To Think and Do,"
IO.puts "With a Beginner's mind"
IO.puts "Let Joy of Doing,"
IO.puts "be my only Reward"
IO.puts "Knowing is not enough"
IO.puts "We must Apply"
IO.puts "Do or do Not,"
IO.puts "There is no Try"
IO.puts "Resolve I shall"
IO.puts "to Finish what I Start."
IO.puts "O! World, my Muse,"
IO.puts "Hello Again!"
